# Site settings
name: Matthew·Cai
description: 'A minimal, single-column Jekyll theme that provides an immersive read experience for your readers'

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://matcai.github.io' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

author:
    name: 'Matthew·Cai'
    email: 'matthewdotcai@gmail.com'
    uri: 'https://github.com/Matcai'

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: false
        duoshuo: true

gems:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate
